name: hummingbird_cli
description: A Flutter CLI tool to kickstart new projects
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.1
  bloc: ^8.1.3
  cli_completion: ">=0.3.0 <0.6.0"
  dartz: ^0.10.1
  flutter_bloc: ^8.1.3
  flutter_riverpod: ^2.4.10
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  hydrated_bloc: ^9.1.4
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  mason_logger: ^0.2.5
  path: ^1.9.0
  provider: ^6.1.2
  pub_updater: ">=0.3.1 <0.5.0"
  replay_bloc: ^0.2.6
  yaml: ^3.1.2

dev_dependencies:
  bloc_test: ^9.1.5
  build_runner: ^2.4.4
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.0
  test: ^1.24.6
  very_good_analysis: ^5.1.0

executables:
  hummingbird:
